services:
  email-scraper:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: email-scraping-service
    restart: unless-stopped
    environment:
      - HUGGINGFACE_MODEL_NAME=Ansh0205/EmailScraping
      - PYTHONUNBUFFERED=1
      - TZ=UTC
    volumes:
      - ./logs:/app/logs:rw
      - ./output:/app/output:rw
      - ./data:/app/data:rw
      - ./.env:/app/.env:ro
      - .:/app:rw
    env_file:
      - .env
    networks:
      - email-scraper-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "python", "-c", "import os; exit(0 if os.path.exists('./email_data.json') else 1)"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  email-scraper-network:
    driver: bridge